
CREATE TABLE CLIENTE (
    NUM_DOCUMENTO VARCHAR2(25),
    TELEFONO VARCHAR2(25) NOT NULL,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    NACIONALIDAD VARCHAR2(25) NOT NULL,
    DIRECCION_FISICA VARCHAR2(100) NOT NULL,
    DIRECCION_ELECTRONICA VARCHAR2(100) NOT NULL,
    DEPARTAMENTO VARCHAR2(50) NOT NULL,
    CODIGO_POSTAL VARCHAR2(25) NOT NULL,
    CIUDAD VARCHAR2(80) NOT NULL,
    TIPO_DOCUMENTO VARCHAR2(25) NOT NULL,
    CONSTRAINT ENUM_TIPOS CHECK (TIPO_DOCUMENTO IN ('NIT', 'CC')),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (NUM_DOCUMENTO));
   
    
    
CREATE TABLE GERENTE_GENERAL (
    NUM_DOCUMENTO VARCHAR2(25),
    TELEFONO VARCHAR2(25) NOT NULL,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    NACIONALIDAD VARCHAR2(25) NOT NULL,
    DIRECCION_FISICA VARCHAR2(100) NOT NULL,
    DIRECCION_ELECTRONICA VARCHAR2(100) NOT NULL,
    DEPARTAMENTO VARCHAR2(50) NOT NULL,
    CODIGO_POSTAL VARCHAR2(25) NOT NULL,
    CIUDAD VARCHAR2(80) NOT NULL,
    TIPO_DOCUMENTO VARCHAR2(25) NOT NULL,
    CONSTRAINT ENUM_TIPOS_DOCUMENTO CHECK (TIPO_DOCUMENTO IN ('NIT', 'CC')),
    CONSTRAINT GERENTE_GENERAL_PK PRIMARY KEY (NUM_DOCUMENTO));
   
    
    
CREATE TABLE GERENTE_DE_OFICINA (
    NUM_DOCUMENTO VARCHAR2(25),
    TELEFONO VARCHAR2(25) NOT NULL,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    NACIONALIDAD VARCHAR2(25) NOT NULL,
    DIRECCION_FISICA VARCHAR2(100) NOT NULL,
    DIRECCION_ELECTRONICA VARCHAR2(100) NOT NULL,
    DEPARTAMENTO VARCHAR2(50) NOT NULL,
    CODIGO_POSTAL VARCHAR2(25) NOT NULL,
    CIUDAD VARCHAR2(80) NOT NULL,
    TIPO_DOCUMENTO VARCHAR2(25) NOT NULL,
    CONSTRAINT ENUM_TIPOS_DOCUM CHECK (TIPO_DOCUMENTO IN ('NIT', 'CC')),
    CONSTRAINT GERENTE_DE_OFICINA_PK PRIMARY KEY (NUM_DOCUMENTO));
    
    
CREATE TABLE CAJERO (
    NUM_DOCUMENTO VARCHAR2(25),
    TELEFONO VARCHAR2(25) NOT NULL,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    NACIONALIDAD VARCHAR2(25) NOT NULL,
    DIRECCION_FISICA VARCHAR2(100) NOT NULL,
    DIRECCION_ELECTRONICA VARCHAR2(100) NOT NULL,
    DEPARTAMENTO VARCHAR2(50) NOT NULL,
    CODIGO_POSTAL VARCHAR2(25) NOT NULL,
    CIUDAD VARCHAR2(80) NOT NULL,
    TIPO_DOCUMENTO VARCHAR2(25) NOT NULL,
    CONSTRAINT ENUM_DOCUMENTO CHECK (TIPO_DOCUMENTO IN ('NIT', 'CC')),
    CONSTRAINT CAJERO_PK PRIMARY KEY (NUM_DOCUMENTO));



CREATE TABLE OFICINA
( ID_OFICINA NUMBER,
    NOMBRE VARCHAR2(25),
    DIRECCION VARCHAR(35),
    PUNTOS_ATENCION NUMBER,
    CONSTRAINT OFICINA_PK PRIMARY KEY (ID_OFICINA)
);


CREATE TABLE OPERACION_BANCARIA 
(ID NUMBER,
VALOR NUMBER NOT NULL,
HORA VARCHAR2(25) NOT NULL,
FECHA DATE NOT NULL,
PRODUCTO VARCHAR2(25) NOT NULL,
TIPO VARCHAR2(25) NOT NULL,
CONSTRAINT ENUM_TIPO CHECK (TIPO IN ('CONSIGNACION', 'RETIRO', 'PEDIR_PRESTAMO', 'PAGAR_PRESTAMO', 'CERRAR_PRESTAMO', 'TRANSFERENCIA')),
CONSTRAINT ENUM_PRODUCTO CHECK (PRODUCTO IN ('CUENTA', 'CDT', 'PRESTAMO')),
CONSTRAINT OPERACION_BANCARIA_PK PRIMARY KEY (ID),
CHECK (VALOR > 0)
); 


CREATE TABLE OPERACION_PRESTAMO
(ID NUMBER,
VALOR NUMBER NOT NULL,
FECHA DATE NOT NULL,
PRESTAMO_AFECTADO NUMBER NOT NULL,
TIPO_OPERACION VARCHAR2(25) NOT NULL,
PRODUCTO_PRESTAMO VARCHAR2(50) NOT NULL,
CONSTRAINT ENUM_TIPO_OPERACION CHECK (TIPO_OPERACION IN ('PAGO_EXTRAORDINARIO', 'PAGO_ORDINARIO')),
CONSTRAINT ENUM_PRODUCTO_PRESTAMO CHECK (PRODUCTO_PRESTAMO IN ('PAGO_DE_LA_CUOTA_MENSUAL', 'PAGO_DE_LA_CUOTA_EXTRAORDINARIA')),
CONSTRAINT OPERACION_PRESTAMO_PK PRIMARY KEY (ID),
CHECK (VALOR > 0)
); 


CREATE TABLE PUNTO_DE_ATENCION
( ID_PUNTO_ATENCION NUMBER,
    LOCALIZACION VARCHAR2(50) NOT NULL,
    TIPO_PUNTO_ATENCION VARCHAR2(50) NOT NULL,
    CONSTRAINT ENUM_TIPO_PUNTO_ATENCION CHECK (TIPO_PUNTO_ATENCION IN ('ATENCION_PERSONALIZADA', 'CAJERO_AUTOMATICO', 'PUNTO_DE_ATENCION_DIGITAL')),
    CONSTRAINT PUNTO_ATENCION_PK PRIMARY KEY (ID_PUNTO_ATENCION)
);


CREATE TABLE PRESTAMO
( ID_PRESTAMO NUMBER,
    MONTO NUMBER,
    INTERES NUMBER,
    NUMERO_CUOTAS NUMBER,
    DIA_PAGO DATE,
    VALOR_CUOTA NUMBER,
    ESTADO_PRESTAMO VARCHAR2(10),
    CATEGORIA VARCHAR2(25),
    CONSTRAINT ENUM_CATEGORIA CHECK (CATEGORIA IN ('ACTIVO', 'CERRADO', 'DESACTIVADO'));
    CONSTRAINT PRESTAMO_ENUM_ESTADO CHECK(ESTADO_PRESTAMO IN ('SOLICITADO', 'APROBADO', 'RECHAZADO', 'PAGADO')),
    CONSTRAINT PRESTAMO_PK PRIMARY KEY (ID_PRESTAMO)
);


CREATE TABLE CUENTA
( NUMERO_CUENTA NUMBER,
    SALDO NUMBER,
    FECHA_ULTIMA_TRANSACCION DATE,
    FECHA_CREACION DATE,
    TIPO_CUENTA VARCHAR2(10),
    ESTADO_CUENTA VARCHAR2(15),
    CONSTRAINT ENUM_TIPO_CUENTA CHECK (TIPO_CUENTA IN ('AHORROS','CORRIENTE', 'AFC')),
    CONSTRAINT ENUM_ESTADO_CUENTA CHECK (ESTADO_CUENTA IN ('ACTIVA', 'CERRADA', 'DESACTIVADA')),
    CONSTRAINT CUENTA_PK PRIMARY KEY (NUMERO_CUENTA)
);


CREATE TABLE PERTENECE
(ID_PUNTO_DE_ATENCION NUMBER NOT NULL,
ID_OFICINA NUMBER NOT NULL,
CONSTRAINT PERTENECE_PK PRIMARY KEY(ID_PUNTO_DE_ATENCION, ID_OFICINA)
);

CREATE TABLE OCURRE
(ID_PUNTO_DE_ATENCION NUMBER NOT NULL,
ID_OPERACION_BANCARIA NUMBER NOT NULL,
CONSTRAINT OCURRE_PK PRIMARY KEY(ID_PUNTO_DE_ATENCION, ID_OPERACION_BANCARIA)
);

CREATE TABLE EJECUTA
(ID_CLIENTE NUMBER NOT NULL,
ID_OPERACION_BANCARIA NUMBER NOT NULL,
CONSTRAINT EJECUTA_PK PRIMARY KEY(ID_CLIENTE, ID_OPERACION_BANCARIA)
);


CREATE TABLE PIDE
(ID_CLIENTE NUMBER NOT NULL,
ID_PRESTAMO NUMBER NOT NULL,
CONSTRAINT PIDE_PK PRIMARY KEY(ID_CLIENTE, ID_PRESTAMO)
);

CREATE TABLE TIENE
(ID_CLIENTE NUMBER NOT NULL,
ID_CUENTA NUMBER NOT NULL,
CONSTRAINT TIENE_PK PRIMARY KEY(ID_CLIENTE, ID_CUENTA)
);


CREATE TABLE HACE
(ID_OPERACION_BANCARIA NUMBER NOT NULL,
ID_CUENTA NUMBER NOT NULL,
CONSTRAINT HACE_PK PRIMARY KEY(ID_CUENTA, ID_OPERACION_BANCARIA)
);

CREATE TABLE MANEJA
(ID_GERENTEOFICINA VARCHAR2(25) NOT NULL,
 ID_OFICINA NUMBER NOT NULL,
 CONSTRAINT MANEJA_PK PRIMARY KEY(ID_OFICINA,ID_GERENTEOFICINA)
 );

ALTER TABLE PERTENECE
ADD CONSTRAINT FK_S_PUNTO_DE_ATENCION
    FOREIGN KEY (ID_PUNTO_DE_ATENCION)
    REFERENCES PUNTO_DE_ATENCION(ID_PUNTO_ATENCION)
    ENABLE;
    
ALTER TABLE PERTENECE
ADD CONSTRAINT FK_S_OFICINA
    FOREIGN KEY (ID_OFICINA)
    REFERENCES OFICINA(ID_OFICINA)
    ENABLE;
    
ALTER TABLE OCURRE
ADD CONSTRAINT FK_S_OPERACION_BANCARIA_OCURRE
    FOREIGN KEY (ID_OPERACION_BANCARIA)
    REFERENCES OPERACION_BANCARIA(ID)
    ENABLE;
    
ALTER TABLE OCURRE
ADD CONSTRAINT FK_S_PUNTO_DE_ATENCION_OCURRE
    FOREIGN KEY (ID_PUNTO_DE_ATENCION)
    REFERENCES PUNTO_DE_ATENCION(ID_PUNTO_ATENCION)
    ENABLE;

ALTER TABLE EJECUTA
ADD CONSTRAINT FK_S_CLIENTE_EJECUTA
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID)
    ENABLE;
    
ALTER TABLE EJECUTA
ADD CONSTRAINT FK_S_OPERACION_BANCARIA_EJECUTA
    FOREIGN KEY (ID_OPERACION_BANCARIA)
    REFERENCES OPERACION_BANCARIA(ID)
    ENABLE;
    
ALTER TABLE PIDE
ADD CONSTRAINT FK_S_CLIENTE_PIDE
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID)
    ENABLE;
    
    
ALTER TABLE PIDE
ADD CONSTRAINT FK_S_PRESTAMO_PIDE
    FOREIGN KEY (ID_PRESTAMO)
    REFERENCES PRESTAMO(ID_PRESTAMO)
    ENABLE;
    
ALTER TABLE TIENE
ADD CONSTRAINT FK_S_CLIENTE
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(NUM_DOCUMENTO)
    ENABLE;
    
ALTER TABLE TIENE
ADD CONSTRAINT FK_S_CUENTA_TIENE
    FOREIGN KEY (ID_CUENTA)
    REFERENCES CUENTA(NUMERO_CUENTA)
    ENABLE;
    
ALTER TABLE HACE
ADD CONSTRAINT FK_S_CUENTA
    FOREIGN KEY (ID_CUENTA)
    REFERENCES CUENTA(NUMERO_CUENTA)
    ENABLE;
    
ALTER TABLE HACE
ADD CONSTRAINT FK_S_OPERACION_BANCARIA_HACE
    FOREIGN KEY (ID_OPERACION_BANCARIA)
    REFERENCES OPERACION_BANCARIA(ID)
    ENABLE;

ALTER TABLE MANEJA
    ADD CONSTRAINT FK_S_OFICINA_MANEJA
    FOREIGN KEY (ID_OFICINA)
    REFERENCES OFICINA(ID_OFICINA)
    ENABLE;

ALTER TABLE MANEJA
    ADD CONSTRAINT FK_S_GERENTE_OFICINA_MANEJA
    FOREIGN KEY (ID_GERENTEOFICINA)
    REFERENCES GERENTE_DE_OFICINA(NUM_DOCUMENTO)
    ENABLE;

